<img style="float: left;" src="pic2.png">

### Sridhar Palle, Ph.D, spalle@emory.edu (Applied ML & DS with Python Program)

<img style = 'float:left;' src = 'nump.jpg'> 

* Numerical Python
* Numpy is the fundamental package for scientific computing with Python
* Much more efficient data storage and operations capability
* Entire ecosystem of python data science tools depend on Numpy

In [1]:
import numpy as np
# Numpy is the linear algebra library for python
np.__version__


'1.15.4'

## 1. Creating Numpy Arrays

### 1.1 Creating Arrays from Scratch

**np.arange(start,stop,step)**

In [2]:
np.arange(10) # Creates numbers 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**np.zeros()**

In [3]:
np.zeros(5) # creates 5 zeroes

array([0., 0., 0., 0., 0.])

**np.ones()**

In [4]:
np.ones(8) # creates an array of 1

array([1., 1., 1., 1., 1., 1., 1., 1.])

**np.eye()**

In [5]:
np.eye(3) # creates identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**np.full()**

In [6]:
np.full((2,3),1) # creates a 2 x 3 array filled with 1.  np.full((nrows,ncols),value)

array([[1, 1, 1],
       [1, 1, 1]])

**np.random.randint()**

In [7]:
np.random.randint(0,10,(3,4)) # creates an 3 x 4 array with random integers between 0 and 10

array([[9, 4, 6, 0],
       [2, 2, 3, 0],
       [0, 6, 3, 3]])

In [ ]:
np.random.randint

In [8]:
np.random.randint(9,20,5) # for just 1d array

array([ 9, 13, 11, 11, 10])

**np.random.random()**

In [9]:
np.random.random((3,4)) # creates a 3 x 4 array with random uniform values between 0 and 1

array([[0.2301802 , 0.93765721, 0.0050638 , 0.7243881 ],
       [0.64277669, 0.40284306, 0.89066622, 0.89286723],
       [0.70508419, 0.77977211, 0.29601017, 0.19744608]])

In [10]:
np.random.rand(3,4) # this is another version with just random.rand(), solves the same purpose as above

array([[0.82672878, 0.84687755, 0.15492076, 0.75741623],
       [0.94749815, 0.19074225, 0.51241275, 0.74255224],
       [0.14902924, 0.74068516, 0.86646553, 0.66335584]])

**np.random.normal()**

In [11]:
np.random.normal(0,1,(4,5)) # creates a 4 x 5 array with normally distributed random values having mean 0 and SD 1

array([[ 1.99079733, -0.49409966,  0.65808624, -0.17733792, -0.48006209],
       [ 0.5090261 ,  0.20858126, -0.56721459, -0.1771347 , -0.1279494 ],
       [ 0.1352109 ,  0.24683416, -0.01797733, -0.38251546, -0.25166664],
       [-0.62342717, -0.8846683 ,  1.27193032, -1.23039122, -0.43204552]])

In [12]:
np.random.randn(4,5) # here mean is by default 0 and SD is 1. Similar to the above method

array([[ 1.07664526, -0.20624324, -1.15397736, -0.99150701,  0.33783711],
       [-0.17397048,  0.74033925, -0.25731851,  0.05553669,  1.0200517 ],
       [-0.20586401, -0.16908683, -0.95503125, -1.02580554, -0.28474449],
       [-0.29907864, -0.5377307 , -1.56455709, -0.17018933,  2.67439999]])

**np.linspace()**

In [13]:
np.linspace(0,10,5) # (start,stop,# of samples), creates an array from 0 to 10 with 5 equally spaced values

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 1.2 Creating numpy arrays fom lists or tuples

In [14]:
np.array([4,5,6])

array([4, 5, 6])

In [15]:
alist = [9, 7, 5, 6]
np.array(alist)

array([9, 7, 5, 6])

In [16]:
atuple = (4, 5, 6, 7)
np.array(atuple)

array([4, 5, 6, 7])

In [17]:
list_list = [[i, i+2] for i in range(0,5)] # List of Lists
list_list

[[0, 2], [1, 3], [2, 4], [3, 5], [4, 6]]

In [23]:
my_arr = np.array(list_list) # creating a 2D numpy array from lists of lists.

In [19]:
my_arr2 = np.arange(10)
my_arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
list(my_arr2) # convert array back to list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
tuple(my_arr2)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

## 2. Indexing, Modifying Arrays

### 2.1 Attributes of Arrays

**.shape** gives the dimensions of an array

In [24]:
my_arr = np.array([[0, 2], [1, 3], [2, 4], [3, 5], [4, 6]])
my_arr

array([[0, 2],
       [1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [25]:
my_arr.shape # .shape gives the shape of the array.

(5, 2)

**ndim**

In [26]:
my_arr.ndim

2

**size**

In [27]:
my_arr.size # total number of elements

10

**.reshape()**

In [28]:
my_arr.reshape(10) # doesn't happen inplace. Original array remains the same.

array([0, 2, 1, 3, 2, 4, 3, 5, 4, 6])

In [29]:
my_arr 

array([[0, 2],
       [1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

### 2.2 Indexing of numpy arrays (similar to lists) npa[start:stop:step]

In [30]:
my_arr2 = np.array([31, 89, 94, 56, 34, 69, 98, 41, 53, 83, 77])
my_arr2

array([31, 89, 94, 56, 34, 69, 98, 41, 53, 83, 77])

***Q. how to get 69***

In [31]:
my_arr2[5]

69

In [32]:
 # indexing works the same way as before

***Q. How to get all the numbers in reverse order***

In [33]:
my_arr2[::-1]

array([77, 83, 53, 41, 98, 69, 34, 56, 94, 89, 31])

In [34]:
my_arr2

array([31, 89, 94, 56, 34, 69, 98, 41, 53, 83, 77])

***Q. Get numbers from 98 to 89 in reverse order***

In [35]:
my_arr2[6:0:-1]

array([98, 69, 34, 56, 94, 89])

**indexing 2D arrays, [start:stop:step, start:stop:step]**

In [36]:
np.random.seed(32) # .seed just makes sure that all of our random numbers match. there is no other meaning
my_arr = np.random.rand(4,5)
my_arr

array([[0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ],
       [0.81620514, 0.10108656, 0.92848807, 0.60910917, 0.59655344],
       [0.09178413, 0.34518624, 0.66275252, 0.44171349, 0.55148779],
       [0.70371249, 0.58940123, 0.04993276, 0.56179184, 0.76635847]])

In [37]:
my_arr[:,:] # my_arr[start:stop:step, start:stop:step]

array([[0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ],
       [0.81620514, 0.10108656, 0.92848807, 0.60910917, 0.59655344],
       [0.09178413, 0.34518624, 0.66275252, 0.44171349, 0.55148779],
       [0.70371249, 0.58940123, 0.04993276, 0.56179184, 0.76635847]])

In [38]:
my_arr[0:2,0:2] # get rows 0,1 and columns 0,1

array([[0.85888927, 0.37271115],
       [0.81620514, 0.10108656]])

In [39]:
# in Python, we generally use ':' after ',' to get all rows or columns. in R just ',' is enough

In [40]:
my_arr[1,:] #get row 1, all columns. In R, just my_arr[2,] would have worked.

array([0.81620514, 0.10108656, 0.92848807, 0.60910917, 0.59655344])

In [41]:
my_arr[:,1] # Get all rows, and column with index 1

array([0.37271115, 0.10108656, 0.34518624, 0.58940123])

In [42]:
my_arr

array([[0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ],
       [0.81620514, 0.10108656, 0.92848807, 0.60910917, 0.59655344],
       [0.09178413, 0.34518624, 0.66275252, 0.44171349, 0.55148779],
       [0.70371249, 0.58940123, 0.04993276, 0.56179184, 0.76635847]])

In [43]:
my_arr[2,2] # to get a particular element

0.6627525231855876

In [44]:
my_arr[1,1:3] # row 1 and columns from 1 to 2

array([0.10108656, 0.92848807])

In [45]:
my_arr

array([[0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ],
       [0.81620514, 0.10108656, 0.92848807, 0.60910917, 0.59655344],
       [0.09178413, 0.34518624, 0.66275252, 0.44171349, 0.55148779],
       [0.70371249, 0.58940123, 0.04993276, 0.56179184, 0.76635847]])

***Q. Get columns 0, 2, 4 in reverse order***

In [46]:
my_arr[:,4::-2]

array([[0.7366696 , 0.55512878, 0.85888927],
       [0.59655344, 0.92848807, 0.81620514],
       [0.55148779, 0.66275252, 0.09178413],
       [0.76635847, 0.04993276, 0.70371249]])

### 2.3 Boolean Masking

**Using conditionals in slicing**

In [47]:
np.random.seed(32)
my_arr = np.random.rand(10)
my_arr

array([0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ,
       0.81620514, 0.10108656, 0.92848807, 0.60910917, 0.59655344])

In [48]:
my_arr > 0.5

array([ True, False,  True,  True,  True,  True, False,  True,  True,
        True])

In [49]:
my_arr[my_arr > 0.5] # get only those array elements whose value is greater than 0.5

array([0.85888927, 0.55512878, 0.95565655, 0.7366696 , 0.81620514,
       0.92848807, 0.60910917, 0.59655344])

In [50]:
np.random.seed(45)
my_arr2D = np.random.rand(3,5)
my_arr2D

array([[0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ],
       [0.47280797, 0.048522  , 0.16332445, 0.11595071, 0.62739168],
       [0.85618205, 0.65010242, 0.99072168, 0.47035075, 0.61829448]])

In [51]:
my_arr2D > 0.5 # get a boolean array 

array([[ True,  True, False, False, False],
       [False, False, False, False,  True],
       [ True,  True,  True, False,  True]])

In [52]:
my_arr2D[my_arr2D > 0.5]

array([0.98901151, 0.54954473, 0.62739168, 0.85618205, 0.65010242,
       0.99072168, 0.61829448])

In [53]:
my_arr2D

array([[0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ],
       [0.47280797, 0.048522  , 0.16332445, 0.11595071, 0.62739168],
       [0.85618205, 0.65010242, 0.99072168, 0.47035075, 0.61829448]])

In [54]:
# Get all rows, for which column 2 values are greater than 0.2

In [55]:
my_arr2D[:,2] > 0.2

array([ True, False,  True])

In [58]:
my_arr2D[(my_arr2D[:,2] > 0.2), 0:2] # Get all rows, for which column 2 values are greater than 0.2

array([[0.98901151, 0.54954473],
       [0.85618205, 0.65010242]])

In [59]:
np.random.seed(32)
my_arr1 = np.random.randint(0,10,6)
my_arr2 = np.random.randint(0,10,6)
print ("my_arr1" + " is " + str(my_arr1))
print ("my_arr2" + " is " + str(my_arr2))

my_arr1 is [7 5 6 8 3 7]
my_arr2 is [9 3 5 9 4 1]


### 2.4 Modifying arrays

In [60]:
import numpy as np
np.random.seed(32)
my_arr = np.random.rand(4,5)
my_arr

array([[0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ],
       [0.81620514, 0.10108656, 0.92848807, 0.60910917, 0.59655344],
       [0.09178413, 0.34518624, 0.66275252, 0.44171349, 0.55148779],
       [0.70371249, 0.58940123, 0.04993276, 0.56179184, 0.76635847]])

In [61]:
my_arr[1,2] = 9
my_arr

array([[0.85888927, 0.37271115, 0.55512878, 0.95565655, 0.7366696 ],
       [0.81620514, 0.10108656, 9.        , 0.60910917, 0.59655344],
       [0.09178413, 0.34518624, 0.66275252, 0.44171349, 0.55148779],
       [0.70371249, 0.58940123, 0.04993276, 0.56179184, 0.76635847]])

In [62]:
my_arr[:,4] = np.array([8, 6, 9, 22]) # replacing all rows of 4th column with new values
my_arr

array([[ 0.85888927,  0.37271115,  0.55512878,  0.95565655,  8.        ],
       [ 0.81620514,  0.10108656,  9.        ,  0.60910917,  6.        ],
       [ 0.09178413,  0.34518624,  0.66275252,  0.44171349,  9.        ],
       [ 0.70371249,  0.58940123,  0.04993276,  0.56179184, 22.        ]])

**appending, inserting, deleting**

In [63]:
np.random.seed(32)
my_arr1D = np.random.randint(0,20,5)
my_arr1D

array([11,  5, 19,  7,  3])

In [64]:
np.append(my_arr1D,100) # add an element at the end. But this is a method on numpy, not on the array object.

array([ 11,   5,  19,   7,   3, 100])

In [65]:
np.insert(my_arr1D,3,200) # insert element at index 3, and with value 2

array([ 11,   5,  19, 200,   7,   3])

In [66]:
my_arr1D # all the above methods, changes not in place.

array([11,  5, 19,  7,  3])

In [67]:
np.delete(my_arr1D,1) # delete element at index 1

array([11, 19,  7,  3])

**Concatenation and splitting**

In [68]:
my_arr1 = np.array([1,2,3, 4])
my_arr2 = np.array([9, 9, 9, 9])

In [69]:
np.vstack([my_arr1,my_arr2]) # vertical stacking

array([[1, 2, 3, 4],
       [9, 9, 9, 9]])

In [70]:
np.hstack([my_arr1,my_arr2]) # horizontal stacking, np.concatenate also does something similar

array([1, 2, 3, 4, 9, 9, 9, 9])

In [71]:
np.random.seed(32)
my_arr = np.random.randint(0,10,(4,5))
my_arr

array([[7, 5, 6, 8, 3],
       [7, 9, 3, 5, 9],
       [4, 1, 3, 1, 2],
       [3, 8, 2, 4, 2]])

In [72]:
upsplit, losplit = np.vsplit(my_arr,[2]) # row index, where the split should happen. also try np.hsplit()

In [73]:
upsplit

array([[7, 5, 6, 8, 3],
       [7, 9, 3, 5, 9]])

In [74]:
losplit

array([[4, 1, 3, 1, 2],
       [3, 8, 2, 4, 2]])

In [75]:
lsplit, rsplit = np.hsplit(my_arr,[2])

In [76]:
lsplit

array([[7, 5],
       [7, 9],
       [4, 1],
       [3, 8]])

In [77]:
rsplit

array([[6, 8, 3],
       [3, 5, 9],
       [3, 1, 2],
       [2, 4, 2]])

**Several More array manipulation methods please see link below**
* https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

**sub arrays are being aliased. If we mutate subarrays, originals are also mutated**

In [ ]:
sub_arr = my_arr[:,1:2]
sub_arr

In [ ]:
sub_arr[:,0] = np.array([9,9,9,9])
sub_arr

In [ ]:
my_arr

### 2.5 UFuncs and Algebraic operations

In [78]:
al = [1,2,3,4] # With lists elementwise operations need for loops, 
# in R however, we can do algebraic operations on vectors directly.

In [79]:
al*4

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [82]:
al + [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [84]:
for i in al:
    print (i*4)

4
8
12
16


In [81]:
[4*i for i in al] # this is more tedious. (Ofcourse list comprehensions are better than traditional for loops)

[4, 8, 12, 16]

**See the power of numpy**

In [85]:
import numpy as np
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
my_arr*4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [87]:
my_arr-500

array([-500, -499, -498, -497, -496, -495, -494, -493, -492, -491])

In [88]:
my_arr/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [89]:
my_arr*5+3 # we can even do operations in an expression. 

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

**All these operations are basically wrappers for built in np. ufunc**

In [ ]:
np.multiply(my_arr,4) # this is same as my_arr*4, similarly we have np.add, np.substract, np.divide etc,=.

**Some more Ufuncs: max, min, mean, sum, sqrt,exp, sin, cos, log, argmin, argmax, std, var, just use np.function**
#### Go to this link https://docs.scipy.org/doc/numpy/reference/ufuncs.html for more functions.


In [90]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.mean(my_arr)

4.5

In [92]:
np.prod(my_arr)

0

In [93]:
np.sum(my_arr) # for several of these aggregating functions, we could also used methods on numpy array object itself (see below)

45

In [94]:
np.sqrt(my_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
np.exp(my_arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

**multi-dimensional aggregation**

In [96]:
np.random.seed(32)
my_arr = np.random.randn(3,5)
my_arr

array([[-0.34889445,  0.98370343,  0.58092283,  0.07028444,  0.77753268],
       [ 0.58195875,  1.47179053,  1.66318101, -0.26117712, -0.68867681],
       [-0.69492326,  1.94042346,  1.80541519,  0.45631385, -0.57481204]])

In [97]:
np.mean(my_arr,0) # specify whether we want to apply the function along rows (0), or columns (1)

array([-0.15395299,  1.46530581,  1.34983968,  0.08847372, -0.16198539])

In [98]:
np.sum(my_arr,1)

array([2.06354893, 2.76707635, 2.9324172 ])

**Methods on numpy objects**

In [ ]:
my_arr.max() # similar to Ufuncs, numpy objects themselves have several methods

In [ ]:
my_arr.sum()

In [ ]:
my_arr.argmax() # index position where maximum value occurs.

***Extras(Optional)***

**Few other numpy methods**

In [ ]:
# np.any, np.all, np.prod, np.bincount, np.where
import numpy as np

In [ ]:
np.random.seed(32)
my_arr = np.random.randint(0,10,20)
my_arr

**np.bincount**

In [ ]:
np.bincount(my_arr) # bincount gives count (frequency) of each value starting from 0 to the largest value.

**np.where**

In [ ]:
np.where(my_arr == 5) # gives the index position where value = 5

**np.sort**

In [ ]:
np.sort(my_arr) # this doesn't happen inplace. To mutate the original use my_arr.sort()

**np.argsort**

In [ ]:
my_arr

In [ ]:
np.argsort(my_arr) # this will give indexes after sorting the array. order(my_arr) does something similar in R.

In [ ]:
np.random.seed(32)
my_arr2D = np.random.rand(4,5)
my_arr2D